== Routenplanung

Die Punkte sindt nur ein Vehikel ( :), pun intended) für die Reiseroute. Ein Grund das man auf die Straße kommt. Die Auswahl ist der Teil den man innerhalb der gemütlichen vier wände machen kann. Hier ist die Träumerei zu erkennen. Abstrakte Orte die Ideen und Vorstellungen entspringen. Die Route ist das Gegenteil sie ist die Konkretisierung und Zusammenführung dieser Ideen. Sie macht es greifbar und zerlegt die Ideen in realisierbare Stücke. Es wird daher nicht auf die Punkte eingegangen. Jeder darf seine eigenen Vorstellungen für sich behalten. Hier geht es um die schmutzigen Fakten zwischen den Ideen. Was passiert wenn man sich einer Idee annähert. Das soll im nachfolgend geplant werden.



concorde
https://hackaday.io/project/158802-improve-tool-path-planning-in-cura/log/147747-using-concorde-tsp-solver

++++
<iframe width="100%" height="900px" frameborder="0" allowfullscreen src="https://umap.openstreetmap.de/de/map/route-idee-deutschland-extrem_5171?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=undefined&captionBar=false"></iframe><p><a href="https://umap.openstreetmap.de/de/map/route-idee-deutschland-extrem_5171">Vollbildanzeige</a></p>
++++

